---
# Install and run Berachain Beacond via Docker with init

- name: Build base folder structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ folder }}"
    - "{{ folder }}/{{ consensus_container_name }}"
    - "{{ folder }}/{{ execution_container_name }}"

- name: Create jwtsecret if it does not exist (Bera requires 0x)
  ansible.builtin.shell: "openssl rand -hex 32 | tr -d '\n' | sed -e 's/^/0x/' > jwtsecret"
  args:
    chdir: "{{ folder }}"
    creates: jwtsecret
    executable: /bin/bash

# Begin berachain beacond initialization
- name: Identify if beacond is initialized
  ansible.builtin.stat:
    path: "{{ folder }}/{{ consensus_container_name }}/config/genesis.json"
  register: node_initialized

- name: Initialize berachain beacond node
  when: not node_initialized.stat.exists
  block:
    - name: Initialize berachain beacond node
      community.docker.docker_container:
        name: "{{ consensus_container_name }}-init"
        image: "ghcr.io/berachain/beacon-kit:{{ consensus_container_version }}"
        state: started
        detach: false
        cleanup: true
        volumes:
          - "{{ folder }}/{{ consensus_container_name }}:/beacond"
        env: "{{ {'CHAIN_SPEC': consensus_chain_spec} if consensus_chain_spec is defined else {} }}"
        command:
          - init
          - "{{ network }}"
          - --chain-id={{ consensus_chain_id }}
          - --home=/beacond

    - name: Replace genesis.json file
      become: true
      ansible.builtin.get_url:
        url: "{{ consensus_genesis }}"
        dest: "{{ folder }}/{{ consensus_container_name }}/config/genesis.json"
        mode: "0644"
        force: true

    - name: Add kzg trusted setup file
      become: true
      ansible.builtin.get_url:
        url: "{{ consensus_kzg_trusted }}"
        dest: "{{ folder }}/{{ consensus_container_name }}/kzg-trusted-setup.json"
        mode: "0644"
        force: true
