---
# Berachain Mainnet
#
# Consensus container client & version
consensus_version: v1.4.1 # Beacond release version
consensus_chain_id: mainnet-beacon-80094

# Consensus Engine Overrides
# consensus_seeds: ""
# consensus_persistent_peers: ""
# suggested_fee_recipient: ""

# Execution container version
execution_container_version: v1.4.1
execution_chain_id: 80094
execution_chain_name: mainnet
